// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGan4gIjEuMISkJssXopzt_TwUMdZxWEw',
    appId: '1:1088176400747:web:14a03f5696d6460d0a842e',
    messagingSenderId: '1088176400747',
    projectId: 'bilal-6c42b',
    authDomain: 'bilal-6c42b.firebaseapp.com',
    storageBucket: 'bilal-6c42b.appspot.com',
    measurementId: 'G-NDT35YTD1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN4TFNwJqw43rOjNrZ0kgic0FK_65f9-k',
    appId: '1:1088176400747:android:8fafca153ff5ab070a842e',
    messagingSenderId: '1088176400747',
    projectId: 'bilal-6c42b',
    storageBucket: 'bilal-6c42b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFFfsCsA03Ey6p_p_DeTvhAoiO354-m68',
    appId: '1:1088176400747:ios:d3ddba79c577c64f0a842e',
    messagingSenderId: '1088176400747',
    projectId: 'bilal-6c42b',
    storageBucket: 'bilal-6c42b.appspot.com',
    iosBundleId: 'com.example.bilal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFFfsCsA03Ey6p_p_DeTvhAoiO354-m68',
    appId: '1:1088176400747:ios:2d4dd4d51f12ae600a842e',
    messagingSenderId: '1088176400747',
    projectId: 'bilal-6c42b',
    storageBucket: 'bilal-6c42b.appspot.com',
    iosBundleId: 'com.example.bilal.RunnerTests',
  );
}
